apisix:
  ssl: 
    enabled: true
    containerPort: 443

service:
  type: LoadBalancer
  tls:
    enabled: true
dashboard:
  enabled: true
ingress-controller:
  enabled: true
  config:
    apisix:
      adminAPIVersion: "v3"
      serviceNamespace: ingress-apisix
    kubernetes:
      enableGatewayAPI: false