# Default values for mssql-latest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 2

image:
  repository: mcr.microsoft.com/mssql/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2022-latest"

SQLCOLLATION:
  value: "SQL_Latin1_General_CP1_CS_AS"

ACCEPT_EULA:
  value: "y"
MSSQL_PID:
  value: "Express"
MSSQL_AGENT_ENABLED:
  value: "false"
SA_PASSWORD:
  secretName: mssql
  key: SA_PASSWORD

containers:
  ports:
    containerPort: 1433

podAnnotations: {}

podSecurityContext:
  fsGroup: 10001

service:
  port: 1433

persistence:
  accessMode:
    - ReadWriteOnce
  size: 2Gi

resources: {}
