sonarWebContext: sonarqube

ingress:
  enabled: true
  ingressClassName: apisix
  hosts:
    - name: sonarqube.localhost
      path: /*
  tls: []

plugins:
  install:
    - https://github.com/vaulttec/sonar-auth-oidc/releases/download/v2.1.1/sonar-auth-oidc-plugin-2.1.1.jar
    - https://github.com/iSergio/sonarqube-community-branch-plugin/releases/download/1.16.1/sonarqube-community-branch-plugin-1.16.1-SNAPSHOT.jar

sonar:
  web:
    javaOpts: "-Dbootstrap.system_call_filter=false;-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.16.1-SNAPSHOT.jar=web"
  ce:
    javaOpts: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.16.1-SNAPSHOT.jar=ce"

postgresql:
  enabled: false

jdbcOverwrite:
  enable: true

resources:
  limits:
    cpu: 800m
    memory: 4Gi
  requests:
    cpu: 400m
    memory: 500M
