sonarWebContext: sonarqube

ingress:
  enabled: true
  ingressClassName: apisix
  hosts:
    - name: sonarqube.localhost
      path: /*
  tls: []

plugins:
  install:
    - https://github.com/vaulttec/sonar-auth-oidc/releases/download/v2.1.1/sonar-auth-oidc-plugin-2.1.1.jar
    - https://github.com/felpasl/sonarqube-community-branch-plugin/releases/download/1.15.0/sonarqube-community-branch-plugin-1.15.0.jar

jvmOpts: "-Dbootstrap.system_call_filter=false;-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.15.0.jar=web"
jvmCeOpts: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.15.0.jar=ce"

persistence:
  size: 1Gi

postgresql:
  enabled: false

jdbcOverwrite:
  enable: true

resources:
  limits:
    cpu: 800m
    memory: 4Gi
  requests:
    cpu: 400m
    memory: 500M
