sonarWebContext: sonarqube

ingress:
  enabled: true
  ingressClassName: apisix
  hosts:
    - name: sonarqube.localhost
      path: /*
  tls: []

plugins:
  install: 
    - https://github.com/vaulttec/sonar-auth-oidc/releases/download/v2.1.1/sonar-auth-oidc-plugin-2.1.1.jar

persistence:
  size: 1Gi

postgresql:
  enabled: false

jdbcOverwrite:
  enable: true