ingress:
  enabled: true
  ingressClassName: apisix
  hosts:
    - name: sonarqube.localhost
      path: /sonar
  annotations: {}
  tls: []

## Path
readinessProbe:
  sonarWebContext: /sonar/
livenessProbe:
  sonarWebContext: /sonar/
startupProbe:
  sonarWebContext: /sonar/
# A custom sonar.properties file can be provided via dictionary.
# For example:
sonarProperties:
  sonar.web.context: /sonar

## Database
jdbcOverwrite: 
  enable: true

postgresql:
  enabled: false      

resources:
  limits:
    cpu: 800m
    memory: 4Gi
  requests:
    cpu: 200m
    memory: 500M

### Branch plugin
plugins:
  install:
    - https://github.com/felpasl/sonarqube-community-branch-plugin/releases/download/1.15.0/sonarqube-community-branch-plugin-1.15.0.jar
    - https://github.com/vaulttec/sonar-auth-oidc/releases/download/v2.1.1/sonar-auth-oidc-plugin-2.1.1.jar
jvmOpts: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.15.0.jar=web"
jvmCeOpts: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.15.0.jar=ce"