apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
spec:
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
        - name: sample-api
          image: swaggerapi/petstore3
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: sample-api
spec:
  selector:
    app: sample-api
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-api
  labels:
    name: sample-api
  annotations:
    k8s.apisix.apache.org/rewrite-target-regex: "/sample/(.*)"
    k8s.apisix.apache.org/rewrite-target-regex-template: "/$1"
spec:
  ingressClassName: apisix
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/sample/"
            backend:
              service:
                name: sample-api
                port:
                  number: 80
