apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: response-add-headers
  namespace: ingress-apisix
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: apisix
  configPatches:
    - applyTo: ROUTE_CONFIGURATION
      patch:
        operation: MERGE
        value:
          response_headers_to_remove:
            - "x-envoy-decorator-operation"
            - "x-envoy-upstream-service-time"
            - "x-kong-response-latency"
            - "server"
          response_headers_to_add:
            - header:
                key: x-xss-protection
                value: "1; mode=block"
              append: false
            - header:
                key: x-frame-options
                value: "SAMEORIGIN"
              append: false
            - header:
                key: x-content-type-options
                value: "nosniff"
              append: false
            - header:
                key: strict-transport-security
                value: "max-age=31536000; preload"
              append: false
