apisix:
  ssl:
    enabled: true
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 500Mi
service:
  type: NodePort #LoadBalancer
  http:
    servicePort: 80
  tls:
    servicePort: 443
    enabled: true
dashboard:
  enabled: true
  ingress:
    enabled: true
    className: apisix
    hosts:
      - host:
        paths:
          - /*
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 500Mi
ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: ingress-apisix
    kubernetes:
      enableGatewayAPI: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 500Mi
etcd:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  persistence:
    size: 1Gi
