apisix:
  ssl:
    enabled: true
service:
  type: NodePort #LoadBalancer
  http:
    servicePort: 80
  tls:
    servicePort: 443
    enabled: true
dashboard:
  enabled: true
  ingress:
    enabled: true
    className: apisix
    hosts:
      - host:
        paths:
          - /*
ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: ingress-apisix
    kubernetes:
      enableGatewayAPI: false
etcd:
  persistence:
    size: 1Gi
