apisix:
  ssl:
    enabled: true
service:
  type: LoadBalancer
  tls:
    enabled: true
dashboard:
  enabled: true
ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: ingress-apisix
    kubernetes:
      enableGatewayAPI: false
etcd:
  persistence:
    size: 1Gi
