apisix:
  ssl:
    enabled: true
service:
  type: NodePort #LoadBalancer
  http:
    servicePort: 80
    nodePort: 31734
  tls:
    servicePort: 443
    nodePort: 31440
    enabled: true
dashboard:
  enabled: true
  ingress:
    enabled: true
    className: apisix
    hosts:
      - host: #sisfolha-dev.intranet.policiamilitar.sp.gov.br
        paths:
          - /apisix-dashboard
ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: ingress-apisix
    kubernetes:
      enableGatewayAPI: false
etcd:
  persistence:
    size: 1Gi
