kind: ConfigMap 
apiVersion: v1 
metadata:
  name: mssql
  annotations:
    {{- include "sql-statefull-deploy.labels" . | nindent 4 }}
data:
  mssql.conf: |
    [EULA]
    accepteula = Y
    accepteulaml = Y
    
    [coredump]
    captureminiandfull = true
    coredumptype = full
    
    [hadr]
    hadrenabled = 1
    
    [language]
    lcid = 1033
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mssql-init
  annotations:
    {{- include "sql-statefull-deploy.labels" . | nindent 4 }}
data:
  init.sh: |
    #!/bin/sh
    /opt/mssql-tools/bin/sqlcmd -S $SQLHOST -U sa -P $SA_PASSWORD -Q "create database sonarqube collate SQL_Latin1_General_CP1_CS_AS";
    /opt/mssql-tools/bin/sqlcmd -S $SQLHOST -U sa -P $SA_PASSWORD -Q "create database keycloak";